- hosts: all
  tasks:
        - package:
                name: "httpd"
                state: present
        - copy:
               dest: "/var/www/html/index.html"
               src: "/root/Desktop/code/index.html"
        - service:
                name: "httpd"
                state: started
        - firewalld:
                port: "80/tcp"
                state: enabled
                immediate: yes
                permanent: yes
