- hosts: all
  vars_prompt:
         - name: ipofjobtracker
           prompt: "Enter the ip of jobtracker"
           private: no

  tasks:
        - template:
               src: /root/Desktop/code/hadoop/Templates/mapredsite.xml
               dest: /etc/hadoop/mapred-site.xml
        
        
